Feature/add remaining token trackers
CeresEcosystem/tools-backend pull request #10
Opened 2023-06-19 15:55 UTC by NikolaCBS

2023-06-19 17:34 UTC, DanijelCBS requested changes

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/dto/formated-token-volume.dto.ts
> +export interface DateTokenVolumeTupleDto {
Wherever you have `volume` in code change to supply.

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/dto/token-volume.dto.ts
> +interface TimestampleVolumeTupleDto {
Volume -> Supply
Timestample -> Timestamp

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/tracker.controller.ts
> +    return await this.trackerService.getTokenSupplyGraph(token);
Rename method in service to `getTokenSupplyData`

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +  private TRACKED_TOKENS: string[] = [];
Since it won't be const anymore, rename it appropriately.

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +  @Cron(CronExpression.EVERY_10_SECONDS)
This cron can be executed once per day.

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +    this.TRACKED_TOKENS = await this.getDestinctTokens();
Using this `getDestinctTokens` method, you only update supply for tokens which are already in the tracker_supply table. Every new added token on Tools won't be affected with this.
So use token price service and its method `findAll` to get all tokens which exist on Ceres Tools.

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +    this.TRACKED_TOKENS = await this.getDestinctTokens();
With that approach, you do not need to manually add PSWAP and VAL.

2023-06-19 17:34 UTC, DanijelCBS commented on src/modules/tracker/seeder/token-supply-seeder.ts
> +import { Console, Command, createSpinner } from 'nestjs-console';
Volume -> Supply

2023-06-20 08:18 UTC, NikolaCBS commented on src/modules/tracker/dto/formated-token-volume.dto.ts
> +export interface DateTokenVolumeTupleDto {
Rename volume to supply

2023-06-20 08:19 UTC, NikolaCBS commented on src/modules/tracker/dto/token-volume.dto.ts
> +interface TimestampleVolumeTupleDto {
Changed text.

2023-06-20 08:20 UTC, NikolaCBS commented on src/modules/tracker/tracker.controller.ts
> +    return await this.trackerService.getTokenSupplyGraph(token);
@DanijelCBS renamed service.

2023-06-20 08:21 UTC, NikolaCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +  private TRACKED_TOKENS: string[] = [];
@DanijelCBS changed variable name to trackedTokens.

2023-06-20 08:23 UTC, NikolaCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +  @Cron(CronExpression.EVERY_10_SECONDS)
@DanijelCBS Changed Cron to be executed everyday at midnight.

2023-06-20 09:08 UTC, NikolaCBS commented on src/modules/tracker/seeder/token-supply-seeder.ts
> +import { Console, Command, createSpinner } from 'nestjs-console';
@DanijelCBS changed name to token-supply-seeder

2023-06-20 09:28 UTC, NikolaCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +    this.TRACKED_TOKENS = await this.getDestinctTokens();
@DanijelCBS Had some trouble using the tokenPriceService so I used the tokenPriceRepository directly inside of the tracker-supply.sync. Have a look at it in the next commit.

2023-06-20 11:05 UTC, DanijelCBS commented on src/modules/tracker/dto/token-volume.dto.ts
> +interface TimestampleVolumeTupleDto {
Forgot to change Timestample to Timestamp.

2023-06-20 11:21 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +    this.TRACKED_TOKENS = await this.getDestinctTokens();
Try to import just TokenPriceModule and then use tokenPriceService's findAll method.

2023-06-20 11:33 UTC, DanijelCBS approved these changes

2023-06-20 11:33 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +//const TRACKED_TOKENS = ['PSWAP', 'VAL'];
If Strahinja approves this approach, you can delete this line.

2023-06-20 19:31 UTC, sstanivuk requested changes

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/tracker.controller.ts
> +  }
Please think about adding cache support as in the endpoint above. Token supply is pretty stable, it changes once a day, so there is no need to fetch it from DB every time. 
1 hour could be a fair cache TTL.

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/tracker-supply.sync.ts
> +  @Cron(CronExpression.EVERY_10_SECONDS)
Actually, I'd advise this to be run at least a couple of times a day, on 4 or 6 hours for example. It is unreliable to have a single chance to sync. If it fails, or the service is restarting at that exact time, we would never get data for that day.

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/seeder/token-supply-seeder.ts
> +    for (let token of tokenNames) {
token can be defined as const

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/seeder/token-supply-seeder.ts
> +        //retry({ count: 10, delay: 1000 }),
please remove the commented-out line.

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/tracker-supply.repository.ts
> +  }
This function seems to be unused. If so, please remove it.

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/tracker-supply.sync.ts
> +//const TRACKED_TOKENS = ['PSWAP', 'VAL'];
sure, please remove the TRACKED_TOKENS  const

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/tracker-supply.sync.ts
> +  private trackedTokens: string[] = [];
I don't like that we are making services stateful. they should not hold anything in memory. 
Imagine that service is restarted and your "every 10 minute" job is relying on the field that is filled only at midnight. 

Please remove this field and the `syncTrackedTokens` function. Instead, invoke the `getTokenNames` function directly in `syncTrackerSupply`.

2023-06-20 19:31 UTC, sstanivuk commented on src/modules/tracker/tracker-supply.sync.ts
>  }
The function could be written in a more readable way: 

```suggestion
  private async getTokenNames(): Promise<string[]> {
    const tokenPrices = await this.tokenPriceService.findAll();
    
    return tokenPrices.map(tokenPrice => tokenPrice.token);
  }
}
```

2023-06-20 21:47 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +  @Cron(CronExpression.EVERY_10_SECONDS)
Twice per day should be enough because new tokens are added very rarely.

2023-06-20 21:52 UTC, DanijelCBS commented on src/modules/tracker/tracker-supply.sync.ts
> +  @Cron(CronExpression.EVERY_10_SECONDS)
However, as I can see in other comments, this function will be removed.

2023-06-21 11:58 UTC, sstanivuk commented on src/modules/tracker/seeder/val-burning-seeder.ts
> +import { Inject, Logger } from '@nestjs/common';
unused import

2023-06-21 11:59 UTC, sstanivuk approved these changes

2023-06-22 05:24 UTC, merged