Add staking, rewards and liquidity to Portfolio
CeresEcosystem/tools-backend pull request #11
Opened 2023-06-21 14:52 UTC by OgnjenCBS

2023-06-21 22:51 UTC, DanijelCBS requested changes

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/dto/liquidity.dto.ts
> +export interface LiquidtyDto {
Fix dto name, there is misspelling.

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.controller.ts
> +  // getPortfolio(@Param('accountId') accountId: string): Promise<PortfolioDto[]> {
Uncomment this method

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.controller.ts
> +  @Get('stake/:accountId')
Set path to `'staking/:accountId'`

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +        `https://farming-api.cerestoken.io/get-pools?accountId=${accountId}`,
Extract fixed part of url to constant.

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +        `https://farming-api.cerestoken.io/get-farms?accountId=${accountId}`,
Extract fixed part of url to constant.

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +      let balance = FPNumber.fromCodecValue(pool.pooledTokens).toNumber();
balance can be const

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +      let stakingReward = FPNumber.fromCodecValue(pool.rewards).toNumber();
stakingReward can be const

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +      let farmingReward = FPNumber.fromCodecValue(pool.rewards).toNumber();
farmingReward can be const

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +      Logger.log(tokenAddress);
Remove logs

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +      let [poolAddress] = (
poolAddress can be const

2023-06-21 22:51 UTC, DanijelCBS commented on src/modules/portfolio/portfolio.service.ts
> +      let liquidityProviding = await this.api.query.poolXYK.poolProviders(
Check all variables which can be const until the end of the file.

2023-06-22 07:18 UTC, sstanivuk commented on src/modules/portfolio/portfolio.service.ts
> +  }
Please create `farming-api-client` module similar to `ceres-client` and place this logic there.

2023-06-22 07:20 UTC, sstanivuk commented on src/modules/portfolio/portfolio.service.ts
> +      this.httpService.get<any>(
please define DTO for the API return value instead of using `any`

2023-06-22 07:20 UTC, sstanivuk commented on src/modules/portfolio/portfolio.service.ts
> +  async fetchStakingData(accountId) {
please define function return type

2023-06-22 13:16 UTC, DanijelCBS approved these changes

2023-06-22 17:26 UTC, sstanivuk approved these changes

2023-06-23 08:49 UTC, merged