Fix/icons service api call retry
CeresEcosystem/tools-backend pull request #13
Opened 2023-06-29 16:08 UTC by NikolaCBS

2023-06-29 16:34 UTC, sstanivuk requested changes
Please rebase your branch on main, so that there are no already merged commits in the PR.

2023-06-29 16:36 UTC, sstanivuk commented on src/modules/icons/icons.service.ts
> +        .pipe(retry({ count: 10, delay: 1000 })),
Nice! Please also add error handling function like we have in other API calls so that we can have more informative error msg in alerting.

2023-06-30 08:27 UTC, NikolaCBS commented on src/modules/icons/icons.service.ts
> +        .pipe(retry({ count: 10, delay: 1000 })),
@sstanivuk roger that. Added error catching capabilities.

2023-06-30 08:57 UTC, sstanivuk commented on src/modules/icons/icons.service.ts
> +            `An error occured while fetching the price off of CoinGecko. ${error.response.data}`,
The error msg is not correct.

2023-06-30 09:27 UTC, closed without merging

2023-06-30 09:27 UTC, NikolaCBS commented
Changed pull request to new one.