Implement swap feature for tools
CeresEcosystem/tools-backend pull request #20
Opened 2023-09-26 11:41 UTC by OgnjenCBS

Created a listener for swaps on chain, which will fill a previously created database with swap data.
Created a http endpoint which will show pages of all previous swaps, based on token searched.
Created a web socket gateway, which tracks live swaps written in the database atm.

2023-09-26 13:20 UTC, DanijelCBS requested changes

2023-09-26 13:20 UTC, DanijelCBS commented on src/modules/swaps/swaps.controller.ts
> +    this.swapDatabase.watchDatabaseChanges(assetId);
With this approach, socket will emit swaps for all tokens to all clients.

2023-09-26 13:24 UTC, Str4LeGit commented on src/modules/swaps/db-connection.service.ts
> +  private onBlockInit: number = 6000;
This can be defined as const above the class as it's not meant to change.

2023-09-26 13:26 UTC, Str4LeGit commented on src/modules/swaps/db-connection.service.ts
> +  private lastCheckedId: number = 0;
This variable is service level, meaning that is shared across the application and thus multiple users. Could it cause any issues having that in mind? 
For example, some users missing swaps because the id changed in the meantime. 
Or when the application restarts, will users be notified of all the swaps once again?

2023-09-26 13:29 UTC, Str4LeGit commented on src/modules/swaps/swaps.controller.ts
> +    this.swapDatabase.watchDatabaseChanges(assetId);
Should each request really trigger the watcher?

2023-09-26 13:34 UTC, Str4LeGit commented on src/modules/swaps/swaps.repository.ts
> +  async writeSwapToDatabase() {
Can we please place this function in a separate class, sync.swaps or listener.swaps for example? 
The repository layer should not be responsible for anything other than db-related things.

2023-09-26 13:37 UTC, Str4LeGit commented on src/modules/swaps/swaps.repository.ts
> +        ) {
In order to avoid nesting, please use the opposite condition and return early. 
https://gomakethings.com/the-early-return-pattern-in-javascript/

2023-09-26 13:41 UTC, Str4LeGit commented on src/modules/swaps/swaps.repository.ts
> +        ) {
Also please add an empty line above loops, if or try statements to make sections more distinct and code more readable. 

For example: 
```
const { event } = record;

if (
     event?.section === 'liquidityProxy' &&
     event?.method === 'Exchange'
) {
```

The exception is when indentation is already in place, so this for example is completelly fine: 
```
} catch (error) {
     if (error instanceof QueryFailedError) {
```

2023-09-27 09:22 UTC, DanijelCBS commented on src/modules/swaps/swap.listener.ts
> +          const swapDto: SwapDto = {
Move this to mapper

2023-09-27 09:23 UTC, DanijelCBS commented on src/modules/swaps/swaps.repository.ts
> +      swaps.push({
Use mapper

2023-09-27 12:42 UTC, DanijelCBS approved these changes

2023-09-28 08:30 UTC, merged