Feature/transactions
CeresEcosystem/tools-backend pull request #32
Opened 2023-11-22 18:20 UTC by OgnjenCBS

2023-11-22 20:40 UTC, Str4LeGit commented on src/modules/transactions/transactions.service.ts
> +  public async transaction(
```suggestion
  public async getTransactionsByAccountId(
```
Or similar

2023-11-22 20:42 UTC, Str4LeGit approved these changes
👍 one minor comment

2023-11-23 09:51 UTC, DanijelCBS requested changes

2023-11-23 09:51 UTC, DanijelCBS commented on src/database/mysql/migrations/1700669840501-create-transactions-table.ts
> +            \`receiver_acc_id\` varchar(255) NOT NULL,
Name this receiver_account_id

2023-11-23 09:51 UTC, DanijelCBS commented on src/modules/transactions/entity/transactions.entity.ts
> +  @Column({ name: 'receiver_acc_id' })
Change it here as well

2023-11-23 09:51 UTC, DanijelCBS commented on src/modules/transactions/entity/transactions.entity.ts
> +  senderAccId: string;
Name it senderAccountId

2023-11-23 09:51 UTC, DanijelCBS commented on src/modules/transactions/entity/transactions.entity.ts
> +  receiverAccId: string;
Name it receiverAccountId

2023-11-23 09:51 UTC, DanijelCBS commented on src/modules/transactions/mapper/tx-entity-to-dto.mapper.ts
> +
Change naming here as well

2023-11-23 09:51 UTC, DanijelCBS commented on src/modules/transactions/transactions.repository.ts
> +      where: [{ senderAccId: accountId }, { receiverAccId: accountId }],
Here as well

2023-11-23 14:35 UTC, DanijelCBS commented on src/modules/transfers/dto/transfer.dto.ts
> +  transferedAt: Date;
Typo, it should be transferredAt

2023-11-23 14:39 UTC, DanijelCBS approved these changes

2023-11-23 15:01 UTC, DanijelCBS approved these changes

2023-11-23 15:02 UTC, merged