Feature/liquidity changes
CeresEcosystem/tools-backend pull request #37
Opened 2023-12-14 09:47 UTC by OgnjenCBS

2023-12-14 11:31 UTC, DanijelCBS requested changes

2023-12-14 11:31 UTC, DanijelCBS commented on src/database/mysql/migrations/1702477525960-create-pairs-periodic-liquidity-change.ts
> +            \`base_asset_id\` varchar(255) NOT NULL,
Base asset id and token asset id are not necessary.

2023-12-14 11:31 UTC, DanijelCBS commented on src/database/mysql/migrations/1702477525960-create-pairs-periodic-liquidity-change.ts
> +            \`liquidity\` int NOT NULL,
Set it to float

2023-12-14 11:31 UTC, DanijelCBS commented on src/modules/pairs-liquidity/dto/pair-periodic-liquidity-change.dto.ts
> +  baseAssetId: string;
Remove IDs

2023-12-14 11:31 UTC, DanijelCBS commented on src/database/mysql/migrations/1702477525960-create-pairs-periodic-liquidity-change.ts
> +            \`base_asset_name\` varchar(255) NOT NULL,
Remove base asset name and token asset name.

2023-12-14 11:31 UTC, DanijelCBS commented on src/modules/pairs-liquidity/pairs-liquidity.controller.ts
> +  @Get('/periodic-difference/:baseSymbol/:tokenSymbol')
Rename periodic-difference to history

2023-12-14 11:31 UTC, DanijelCBS commented on src/modules/pairs-liquidity/pairs-liquidity.service.ts
> +    baseAssetSy: string,
Rename to full name baseAssetSymbol

2023-12-14 11:31 UTC, DanijelCBS commented on src/modules/pairs-liquidity/periodic-liquidity-change.repository.ts
> +    baseAssetSy: string,
Rename to full name

2023-12-14 12:34 UTC, DanijelCBS approved these changes

2023-12-15 08:11 UTC, Str4LeGit commented on src/modules/pairs-liquidity/pairs-liquidity.controller.ts
> +    return this.pairsLiquidityChangesService.getPeriodicChanges(
Do we need pagination here? I guess that response can get pretty big in a short time.

2023-12-15 08:12 UTC, Str4LeGit commented on src/modules/pairs-liquidity/pairs-liquidity.service.ts
> +      pairLiqChange.updatedAt = new Date();
This should ideally be moved to a mapper class.

2023-12-15 09:22 UTC, Str4LeGit approved these changes

2023-12-15 16:40 UTC, merged