Feature/swaps filters
CeresEcosystem/tools-backend pull request #38
Opened 2023-12-14 11:11 UTC by sdjuka

2023-12-14 11:38 UTC, DanijelCBS requested changes

2023-12-14 11:38 UTC, DanijelCBS commented on src/modules/swaps/dto/swap-options.dto.ts
> +const DEFAULT_MAX_AMOUNT = 1000000000;
Put max value for number here

2023-12-14 11:38 UTC, DanijelCBS commented on src/modules/swaps/swaps.repository.ts
> +    if (whereClauses.length > 0) {
Unnecessary check

2023-12-14 11:38 UTC, DanijelCBS commented on src/modules/swaps/swaps.repository.ts
> +  private getWhereClauses(swapOptions: SwapOptionsDto): WhereClause[] {
Move this function to the end of file

2023-12-15 08:24 UTC, Str4LeGit approved these changes
Very nice! I like the way you documented dto fields.

2023-12-15 09:08 UTC, DanijelCBS approved these changes

2023-12-15 09:32 UTC, merged