Feature/token holders
CeresEcosystem/tools-backend pull request #42
Opened 2023-12-25 12:54 UTC by OgnjenCBS

2023-12-25 13:25 UTC, DanijelCBS requested changes

2023-12-25 13:25 UTC, DanijelCBS commented on src/modules/token-holders/token-holders.service.ts
> +  public async getHoldersAndBalances(
Move this method to the top.

2023-12-25 13:25 UTC, DanijelCBS commented on src/modules/token-holders/token-holders.service.ts
> +  private async updateHolders(): Promise<void> {
Move this method to be the 2nd in the file.

2023-12-25 13:25 UTC, DanijelCBS commented on src/modules/token-holders/token-holders.service.ts
> +  private async removeZeroBalances(): Promise<void> {
Check if this can be done in the repo with delete method and where condition.

2023-12-25 15:20 UTC, DanijelCBS approved these changes

2023-12-26 10:37 UTC, Str4LeGit commented on src/database/mysql/migrations/1703504742036-create-holders-token-balances.ts
> +            \`holder\` varchar(255) NOT NULL,
Is this address format? We should limit the length to 40 or 50, 255 is not necessary.

2023-12-26 10:37 UTC, Str4LeGit commented on src/database/mysql/migrations/1703504742036-create-holders-token-balances.ts
> +            \`token\` varchar(255) NOT NULL,
Same here.

2023-12-26 10:37 UTC, Str4LeGit commented on src/modules/token-holders/token-holders.service.ts
> +                .div(FPNumber.fromNatural(10 ** 18))
There should be denominator constant that can be reused.

2023-12-26 13:06 UTC, Str4LeGit approved these changes

2023-12-26 13:07 UTC, merged