Volume calculation and trading chart data
CeresEcosystem/tools-backend pull request #54
Opened 2024-02-10 21:48 UTC by Str4LeGit

2024-02-12 09:17 UTC, DanijelCBS requested changes

2024-02-12 09:17 UTC, DanijelCBS commented on src/modules/swaps/swaps.repository.ts
> +  async findSwapsForVolumes(): Promise<SwapDto[]> {
This approach will fetch volumes for the last 5 minutes which could lead to the missing data (for example, if app is not running for few minutes).

2024-02-14 12:55 UTC, OgnjenCBS approved these changes

2024-02-14 22:57 UTC, DanijelCBS approved these changes

2024-02-15 21:48 UTC, merged