Track buys and sells for swaps
CeresEcosystem/tools-backend pull request #61
Opened 2024-03-25 17:04 UTC by sdjuka

2024-03-26 10:09 UTC, DanijelCBS requested changes

2024-03-26 10:09 UTC, DanijelCBS commented on src/modules/swaps/swaps.repository.ts
> +
Pass `data ` as a parameter to function instead of `queryBuilder`.

```suggestion
const length = data.length;
const buys = data.filter(swap => swap.outputAssetId === assetId).length;
const sells = length - buys;

return {
      buys,
      sells,
    };
```

2024-03-26 20:50 UTC, Str4LeGit commented on src/modules/swaps/dto/swaps-page.dto.ts
> +export class SwapsPageDto<T> extends PageDto<T> {
I previously implemented a generic structure for this purposes. `PageWithSummaryDto`. Please take a look at it and how it's used in `kensetsu.service.ts`. Idea is that Summary object can take whatever form you need, in this case, that would be `SwapsStatsDto`.

2024-03-26 20:52 UTC, Str4LeGit commented on src/modules/swaps/swaps.controller.ts
> +  ): Promise<SwapsPageDto<SwapDto>> {
As in previous comment, please try to use `PageWithSummaryDto`. Let me know if there are any issues.

2024-03-26 21:00 UTC, Str4LeGit commented on src/modules/swaps/swaps.repository.ts
> +
@DanijelCBS I believe that what @sdjuka needs is amount and not count of buys/sells.

2024-03-26 21:01 UTC, Str4LeGit commented on src/modules/swaps/swaps.repository.ts
> +    const [data] = await queryBuilder.getManyAndCount();
You can use `getMany` function as you're not using count part.

2024-03-26 21:10 UTC, Str4LeGit commented on src/modules/swaps/swaps.repository.ts
> +    const [data] = await queryBuilder.getManyAndCount();
Also, I think we should use dedicated query to fetch buy/sell amounts. A query that would do calculation in db itself. This way, API performance could be affected as there can be tons of rows that needs to be fetched and calculated in memory.

That would look like examples you can find in:
- kensetsu.service.ts: getAmountBurnedTotal
- tracker-burn.service.ts: aggregateBurningGraphData
- tracker-summary.service.ts: aggregateBurningSummaryForPeriod

With a single request you could fetch sum for `assetInputAmount` and `assetOutputAmount`.

2024-03-26 22:17 UTC, Str4LeGit approved these changes

2024-03-27 00:19 UTC, DanijelCBS approved these changes

2024-03-27 08:39 UTC, merged